---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ficl4036/public_html/site-projet3
    - mkdir -p $DEPLOYPATH
    - rm -rf $DEPLOYPATH/*
    - cd /home/ficl4036/02Sites
    - npm install --omit=dev
    - npm run build
    - cp -R build/* $DEPLOYPATH
